name: Compress images

# Environment variables
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

# Controls when the action will run.
on:
  push:
    branches:
      - main
    paths:
      - "icons/**"
      - ".github/workflows/compress-images.yml"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  validate:
    runs-on: windows-2022
    #runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Import GPG key
      - name: Import GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.GPGKEY }}
          passphrase: ${{ secrets.GPGPASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true
          git_config_global: true
          git_tag_gpgsign: true
          git_push_gpgsign: false

      - name: Install modules
        shell: pwsh
        working-directory: "${{ github.workspace }}"
        run: |
            [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
            Install-PackageProvider -Name "NuGet" -MinimumVersion "2.8.5.208" -Force -ErrorAction "SilentlyContinue"
            if (Get-PSRepository -Name "PSGallery" | Where-Object { $_.InstallationPolicy -ne "Trusted" }) {
                Set-PSRepository -Name "PSGallery" -InstallationPolicy "Trusted" -ErrorAction "SilentlyContinue"
            }
            $Module = "Pester"
            if ([System.Version]((Find-Module -Name $Module).Version) -gt (Get-Module -Name $Module).Version) {
                Install-Module -Name $Module -SkipPublisherCheck -Force
            }
            Import-Module -Name $Module -Force

      # Run Pester tests
      - name: Test images
        shell: pwsh
        working-directory: "${{ github.workspace }}"
        run: |
            $Config = [PesterConfiguration]::Default
            $Config.Run.Path = "$projectRoot\tests"
            $Config.Run.PassThru = $True
            $Config.TestResult.Enabled = $True
            $Config.TestResult.OutputFormat = "NUnitXml"
            $Config.TestResult.OutputPath = "$projectRoot\TestsResults.xml"
            Invoke-Pester -Configuration $testConfig

      - name: Compress images
        shell: pwsh
        working-directory: "${{ github.workspace }}"
        run: |
            $params = @{
                Path = "${{ github.workspace }}"
            }
            . .\scripts\Optimise-Images.ps1 @params

      - name: Commit changes
        id: commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update json ${{ steps.get-date.outputs.date }}.${{ github.run_number }} ${{ github.job }}"
          commit_user_name: ${{ secrets.COMMIT_NAME }}
          commit_user_email: ${{ secrets.COMMIT_EMAIL }}

      - name: "Run if changes have been detected"
        if: steps.commit.outputs.changes_detected == 'true'
        run: echo "Changes committed."

      - name: "Run if no changes have been detected"
        if: steps.commit.outputs.changes_detected == 'false'
        run: echo "No changes detected."
